name: subscription-manager
dependencies:
  - _libgcc_mutex=0.1=main
  - atomicwrites=1.3.0=py37_1
  - attrs=19.1.0=py37_1
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py37_0
  - click=7.0=py37_0
  - coverage=4.5.4=py37h7b6447c_0
  - flask=1.1.1=py_0
  - flask-sqlalchemy=2.4.0=py_0
  - importlib_metadata=0.23=py37_0
  - itsdangerous=1.1.0=py37_0
  - jinja2=2.10.1=py37_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - more-itertools=7.2.0=py37_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1d=h7b6447c_1
  - packaging=19.2=py_0
  - pip=19.2.3=py37_0
  - pluggy=0.13.0=py37_0
  - py=1.8.0=py37_0
  - pyparsing=2.4.2=py_0
  - pytest=5.0.1=py37_0
  - pytest-cov=2.7.1=py_0
  - python=3.7.4=h265db76_1
  - readline=7.0=h7b6447c_5
  - setuptools=41.2.0=py37_0
  - six=1.12.0=py37_0
  - sqlalchemy=1.3.8=py37h7b6447c_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wcwidth=0.1.7=py37_0
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - alembic==1.2.1
    - broker-rest-client==0.0.6
    - chardet==3.0.4
    - clickclick==1.2.2
    - connexion==2.3.0
    - flask-migrate==2.5.2
    - gunicorn==19.9.0
    - idna==2.8
    - inflection==0.3.1
    - jsonschema==2.6.0
    - mako==1.1.0
    - marshmallow==3.2.0
    - marshmallow-sqlalchemy==0.19.0
    - openapi-spec-validator==0.2.8
    - psycopg2-binary==2.8.3
    - python-dateutil==2.8.0
    - python-editor==1.0.4
    - pyyaml==5.1.2
    - requests==2.22.0
    - rest-client==0.0.8
    - swagger-ui-bundle==0.0.5
    - swim-backend==0.0.4
    - urllib3==1.25.6
