name: subscription-manager
dependencies:
  - atomicwrites=1.3.0=py37_1
  - attrs=19.1.0=py37_1
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - click=7.0=py37_0
  - coverage=4.5.3=py37h7b6447c_0
  - flask=1.0.2=py37_1
  - flask-sqlalchemy=2.3.2=py37_0
  - itsdangerous=1.1.0=py37_0
  - jinja2=2.10=py37_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - markupsafe=1.1.1=py37h7b6447c_0
  - more-itertools=6.0.0=py37_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1b=h7b6447c_1
  - pip=19.0.3=py37_0
  - pluggy=0.9.0=py37_0
  - py=1.8.0=py37_0
  - pytest=4.3.1=py37_0
  - pytest-cov=2.6.1=py37_0
  - python=3.7.3=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=40.8.0=py37_0
  - six=1.12.0=py37_0
  - sqlalchemy=1.3.1=py37h7b6447c_0
  - sqlite=3.27.2=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - werkzeug=0.14.1=py37_0
  - wheel=0.33.1=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - chardet==3.0.4
    - clickclick==1.2.2
    - connexion==2.2.0
    - idna==2.8
    - inflection==0.3.1
    - jsonschema==2.6.0
    - marshmallow==2.19.2
    - marshmallow-sqlalchemy==0.16.1
    - openapi-spec-validator==0.2.6
    - pathlib==1.0.1
    - psycopg2-binary==2.7.7
    - pyjwt==1.7.1
    - pyyaml==5.1
    - requests==2.21.0
    - swagger-ui-bundle==0.0.3
    - urllib3==1.24.1
